# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: DEV
  jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    displayName: 'Build and Deploy to DEV'
    variables:
    - group: env-webapp-dev
    steps:
    - task: ManualIntervention@8
      inputs:
        instructions: 'Approval Pending'

    - task: CmdLine@2
      inputs:
        script: |
          (
            echo VUE_APP_VARIABLE=$(VUE_APP_VARIABLE)
          ) > .env
          cat .env
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        repository: 'vue-app'
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: 'latest'
    - task: ECRPushImage@1
      displayName:  'Push Docker Image to ECR'
      inputs:
        awsCredentials: 'AWS'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: 'vue-app'
        repositoryName: 'vue-app'
    - task: AWSCLI@1
      displayName: 'Restart ECS service'
      inputs:
        awsCredentials: 'AWS'
        regionName: 'us-east-1'
        awsCommand: 'ecs'
        awsSubCommand: 'update-service'
        awsArguments: '--cluster dev-cluster --service deployment-service --force-new-deployment'
- stage: PROD
  jobs:
  - deployment: deploy
    displayName: Build and deploy to PROD
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 'DEVELOPMENT'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploying to PROD