# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages: 
- stage: PROD 2do Pipeline
  lockBehavior: runLatest
  jobs:
  - deployment: deploy
    displayName: 'Build and Deploy to DEV'
    environment: DEVELOPMENT
    variables:
    - group: env-webapp-dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploted_to_DEV from 2nd pipeline
