# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pr: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: DEV
  jobs:
  - job: build
    variables:
    - group: env-webapp-dev
    steps:
    - task: CmdLine@2
      displayName: Create ENV File
      inputs:
        script: |
          (
            echo DB_PASSWORD=\$\$VUE_APP_DB_PASSWORD\$\$
          ) > .env
          cat .env
    - task: replacetokens@5
      inputs:
        targetFiles: '.env'
        tokenPrefix: '$$'
        tokenSuffix: '$$'