# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pr: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: DEV
  jobs:
  - job: build
    variables:
    - group: env-webapp-dev
    steps:
    - task: CmdLine@2
      displayName: Create ENV File
      inputs:
        script: |
          (
            echo DB_PASSWORD=\$\$VUE_APP_DB_PASSWORD\$\$
          ) > .env
          cat .env
    - task: replacetokens@5
      inputs:
        targetFiles: '.env'
        encoding: 'auto'
        tokenPattern: 'custom'
        tokenPrefix: '$$'
        tokenSuffix: '$$'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: true
    - task: Docker@2
      inputs:
        containerRegistry: 'AWS Private ECR'
        repository: 'vue-app'
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: 'latest'
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AWS'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: 'vue-app'
        repositoryName: 'vue-app'
    - task: AWSCLI@1
      inputs:
        awsCredentials: 'AWS'
        regionName: 'us-east-1'
        awsCommand: 'ecs'
        awsSubCommand: 'update-service'
        awsArguments: '--cluster dev-cluster --service deployment-service --force-new-deployment'